import { prisma } from './prisma'

// Spread dates across the last 5 months
function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}

const tickets = [
  // ── GENERAL QUESTIONS ─────────────────────────────────────────────────────
  {
    senderName: 'Alice Johnson',
    senderEmail: 'alice.johnson@gmail.com',
    subject: 'Where can I find my invoice?',
    body: 'Hi, I need a copy of my invoice from last month for expense reporting. I checked my email but cannot find it. Could you point me in the right direction?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Bob Martinez',
    senderEmail: 'bob.m@outlook.com',
    subject: 'How do I change my account email address?',
    body: "I recently changed my work email and need to update it on my account. I don't see this option in account settings. Is there a way to do this, or do I need to contact support?",
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(10),
  },
  {
    senderName: 'Charlie Lee',
    senderEmail: 'charlie@techcorp.io',
    subject: 'What are your support hours?',
    body: 'We are based in Singapore (UTC+8) and need to know when your support team is available. Do you offer 24/7 support or are there specific hours?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(15),
  },
  {
    senderName: 'Diana Prince',
    senderEmail: 'diana.p@yahoo.com',
    subject: 'How do I cancel my subscription?',
    body: 'I would like to cancel my subscription at the end of the current billing period. I have not been using the service much lately. Please advise on the cancellation process.',
    status: 'CLOSED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(45),
  },
  {
    senderName: 'Ethan Williams',
    senderEmail: 'e.williams@startup.co',
    subject: 'Do you offer student discounts?',
    body: 'I am a university student working on a side project. I noticed there is no student plan listed on your pricing page. Do you offer any discounts for students or academic institutions?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Fiona Chen',
    senderEmail: 'fiona.chen@enterprise.com',
    subject: 'How do I update my billing address?',
    body: 'Our company recently moved offices and I need to update the billing address on our account to reflect the new location. The invoices still show our old address.',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(20),
  },
  {
    senderName: 'George Kumar',
    senderEmail: 'george.k@webmail.net',
    subject: 'Is there a mobile app available?',
    body: 'I travel frequently and would love to access the service from my phone. I searched the App Store and Google Play but could not find an official app. Do you have one or are there plans to release one?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(1),
  },
  {
    senderName: 'Hannah Smith',
    senderEmail: 'hannah.smith@icloud.com',
    subject: 'Can I add multiple users to my account?',
    body: 'I have a small team of 5 people and we all need access. Does the current plan I am on allow multiple users, or do I need to upgrade to a team plan?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(30),
  },
  {
    senderName: 'Ivan Petrov',
    senderEmail: 'ivan.p@company.ru',
    subject: 'What payment methods do you accept?',
    body: 'I want to subscribe but my company policy requires payment via bank transfer. Do you support wire transfers or SEPA payments in addition to credit cards?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Julia Roberts',
    senderEmail: 'julia.r@proton.me',
    subject: 'How do I export all my data?',
    body: 'I would like to export all data associated with my account as part of our GDPR compliance audit. What formats are available and how long does the export take?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Kevin O\'Brien',
    senderEmail: 'kevin.ob@gmail.com',
    subject: 'Do you offer a free trial?',
    body: 'I want to evaluate the product before committing to a paid plan. Your website mentions a free trial but I could not find a button to start one. How do I get access?',
    status: 'CLOSED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(60),
  },
  {
    senderName: 'Laura Müller',
    senderEmail: 'l.muller@gmx.de',
    subject: 'How do I change my password?',
    body: 'I would like to update my password to something more secure. I went to Account Settings but only see options to change name and email. Where is the password change option?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(22),
  },
  {
    senderName: 'Michael Thompson',
    senderEmail: 'mike.t@business.com',
    subject: 'Can I pause my subscription instead of cancelling?',
    body: 'We are going through a quiet period and would like to pause our subscription for 2–3 months rather than cancelling entirely. Is this something you support?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Nina Patel',
    senderEmail: 'nina.patel@hotmail.com',
    subject: "What's the difference between the Pro and Business plans?",
    body: 'I am trying to decide between the Pro and Business plans. Your pricing page lists different features but I am not clear on the practical differences for a team of 10. Could you clarify?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(18),
  },
  {
    senderName: 'Oliver Brown',
    senderEmail: 'oliver.b@freelance.io',
    subject: 'Do you offer annual billing discounts?',
    body: 'I have been on the monthly plan for 6 months now. Is there a discount if I switch to annual billing, and can I do that mid-cycle?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(35),
  },
  {
    senderName: 'Patricia Davis',
    senderEmail: 'patricia.d@corp.net',
    subject: 'How do I delete my account permanently?',
    body: 'I have decided to stop using the service and want to ensure all my personal data is permanently deleted. Please confirm the account deletion process and how long it takes.',
    status: 'CLOSED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(75),
  },
  {
    senderName: 'Quinn Anderson',
    senderEmail: 'quinn.a@gmail.com',
    subject: 'What currencies do you support for billing?',
    body: 'I am in Brazil and would like to be billed in BRL to avoid foreign transaction fees. Do you support billing in local currencies, or is everything charged in USD?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(7),
  },
  {
    senderName: 'Rachel Green',
    senderEmail: 'r.green@centralpark.com',
    subject: 'How do I set up two-factor authentication?',
    body: 'Our IT department is requiring all SaaS tools to have 2FA enabled for security compliance. I cannot find the 2FA setup option in my security settings. Could you guide me?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(12),
  },
  {
    senderName: 'Sam Wilson',
    senderEmail: 'sam.w@shield.gov',
    subject: 'What is your data retention policy?',
    body: 'For our compliance requirements, I need written confirmation of how long you retain customer data after account deletion. Please share your data retention policy document.',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(8),
  },
  {
    senderName: 'Tina Turner',
    senderEmail: 'tina.t@rockstar.com',
    subject: 'How do I download all my receipts at once?',
    body: 'I need all my receipts from 2025 for tax purposes. Downloading them one by one is very tedious. Is there a bulk export or ZIP download option?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(9),
  },
  {
    senderName: 'Ursula Wagner',
    senderEmail: 'u.wagner@deutsch.de',
    subject: 'Is your service available in German?',
    body: 'Our team is primarily German-speaking. Is there a German localisation available, or is the interface English-only? We would appreciate a localised experience.',
    status: 'CLOSED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(90),
  },
  {
    senderName: 'Victor Huang',
    senderEmail: 'v.huang@techventures.cn',
    subject: 'Can I use your API without a paid plan?',
    body: 'I want to integrate your API into a personal project. Is there a free tier for API access, or does it require a paid subscription?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(40),
  },
  {
    senderName: 'Wendy Clarke',
    senderEmail: 'wendy.c@nonprofit.org',
    subject: 'Do you offer discounts for nonprofits?',
    body: 'We are a registered 501(c)(3) nonprofit organisation. We love your product but the standard pricing is above our budget. Do you have a nonprofit or charity pricing tier?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(11),
  },
  {
    senderName: 'Xander Fox',
    senderEmail: 'x.fox@agency.co',
    subject: 'How do I manage client workspaces?',
    body: 'I run a digital agency and manage accounts for multiple clients. Is there a way to switch between client workspaces without logging out and back in each time?',
    status: 'OPEN' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(13),
  },
  {
    senderName: 'Yuki Tanaka',
    senderEmail: 'yuki.t@design.jp',
    subject: 'Is there an affiliate or referral program?',
    body: 'I have several colleagues who would benefit from your service. Do you have a referral program where I could earn credits or commissions for bringing in new customers?',
    status: 'RESOLVED' as const,
    category: 'GENERAL_QUESTION' as const,
    createdAt: daysAgo(28),
  },

  // ── TECHNICAL QUESTIONS ───────────────────────────────────────────────────
  {
    senderName: 'Aaron Brooks',
    senderEmail: 'aaron.b@devteam.io',
    subject: 'Cannot log into my account — password correct',
    body: 'I know my password is correct because I just reset it, but I still cannot log in. I get an "Invalid credentials" error every time. Tried three different browsers with no luck.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(1),
  },
  {
    senderName: 'Beth Collins',
    senderEmail: 'beth.c@webstudio.net',
    subject: 'Dashboard fails to load — blank white screen',
    body: 'After logging in, the dashboard just shows a blank white page. The browser console shows: "Uncaught TypeError: Cannot read properties of undefined (reading \'map\')" on dashboard.js:142.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(14),
  },
  {
    senderName: 'Carlos Ruiz',
    senderEmail: 'c.ruiz@apifirst.dev',
    subject: 'API requests returning 401 even with valid token',
    body: 'Our API calls started failing with 401 Unauthorized responses about 2 hours ago. The token was issued yesterday and has not expired. Nothing changed on our end. Is there a server-side issue?',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Deborah Nkosi',
    senderEmail: 'deb.nkosi@fintech.za',
    subject: 'Slack integration stopped posting notifications',
    body: 'Our Slack integration was working fine until 3 days ago. Now no notifications are appearing in our #alerts channel. The integration shows as "Connected" in settings but nothing comes through.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(16),
  },
  {
    senderName: 'Elliot Nash',
    senderEmail: 'e.nash@webhooks.dev',
    subject: 'Webhook endpoint not receiving any events',
    body: 'I set up a webhook endpoint at https://api.myapp.com/hooks/ticketmaster and verified it responds with 200. However, I am not receiving any events. The delivery logs in your dashboard show "Failed: Connection refused".',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Faye Morrison',
    senderEmail: 'faye.m@dataops.co',
    subject: 'CSV export is completely empty',
    body: 'When I click "Export to CSV" on the reports page, it downloads a file that only contains the header row and no data. I have 200+ records that should be included. This started after last Tuesday\'s update.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Greg Santos',
    senderEmail: 'g.santos@mobile.br',
    subject: 'Authenticator app code not accepted for 2FA',
    body: 'I set up 2FA with Google Authenticator but the 6-digit codes are being rejected. I have checked that my phone time is synced correctly. Is there a known issue with TOTP authentication?',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(25),
  },
  {
    senderName: 'Holly Reed',
    senderEmail: 'h.reed@searchco.io',
    subject: 'Search returning results from wrong workspace',
    body: 'Our global search is returning results from a different workspace. When I search for "Q4 report" I get documents from another company\'s account. This is a serious data isolation issue.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(1),
  },
  {
    senderName: 'Isaac Levy',
    senderEmail: 'i.levy@cloudmail.com',
    subject: 'Email notifications not being delivered',
    body: 'I have email notifications enabled for all events but stopped receiving them 5 days ago. Checked spam folder and nothing there. Other emails from your domain arrive fine, just not notification emails.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Jessica Park',
    senderEmail: 'j.park@chromeweb.kr',
    subject: 'Browser extension crashes on Chrome 122',
    body: 'Since updating Chrome to version 122, your browser extension crashes immediately on load. The extension worked fine on 121. I\'ve tried reinstalling but same result. Error: "Extension context invalidated".',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(30),
  },
  {
    senderName: 'Karl Hoffmann',
    senderEmail: 'k.hoffmann@enterprise.de',
    subject: 'SAML SSO configuration is not saving',
    body: 'Every time I enter our IdP metadata and click Save in the SSO settings, the page reloads and shows the fields empty again. Our security team is waiting on this to roll out SSO company-wide.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Lena Johansson',
    senderEmail: 'lena.j@nordic.se',
    subject: 'Hitting API rate limit with normal usage',
    body: 'We are getting 429 Rate Limit Exceeded errors during normal business hours, even though we are well under the documented limits of 1000 req/min. Are there undocumented limits we should know about?',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(7),
  },
  {
    senderName: 'Marco Bianchi',
    senderEmail: 'm.bianchi@italtech.it',
    subject: 'App freezes on mobile Safari iOS 17',
    body: 'The web app freezes completely when trying to edit any text field on Safari iOS 17. A hard refresh fixes it temporarily but the issue returns after a minute or two. Works fine on Safari desktop.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(20),
  },
  {
    senderName: 'Naomi Clarke',
    senderEmail: 'n.clarke@bulkops.com',
    subject: 'Bulk CSV import fails on files over 5MB',
    body: 'The bulk import feature works for small files but consistently fails with a generic "Import failed" error for files over 5MB. I have a 12MB file with 50,000 records I need to import.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(8),
  },
  {
    senderName: 'Omar Hassan',
    senderEmail: 'o.hassan@analytics.ae',
    subject: 'Date formatting incorrect for Middle East locale',
    body: 'Reports show dates in MM/DD/YYYY format but our region uses DD/MM/YYYY. I have set my locale to Arabic (AE) in profile settings but the report dates still use the US format.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(38),
  },
  {
    senderName: 'Priya Sharma',
    senderEmail: 'p.sharma@uxlab.in',
    subject: 'Drag and drop broken after v2.4 update',
    body: 'Since the v2.4 update yesterday, drag and drop reordering on the Kanban board no longer works. Dragging a card picks it up visually but dropping it has no effect. Worked fine before the update.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(17),
  },
  {
    senderName: 'Robert Quinn',
    senderEmail: 'r.quinn@backenddev.ca',
    subject: '404 on webhook verification endpoint',
    body: 'Your documentation says to verify webhooks by sending a GET to /api/webhooks/verify but that endpoint returns 404. I\'ve double-checked the URL and API version (v3). Is the docs out of date?',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(9),
  },
  {
    senderName: 'Sophie Laurent',
    senderEmail: 's.laurent@oauth.fr',
    subject: 'OAuth redirect_uri mismatch error',
    body: 'Our OAuth flow is failing with "redirect_uri_mismatch" error even though the redirect URI in the developer console exactly matches what we send. It was working last week without any changes on our side.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Thomas Eriksson',
    senderEmail: 't.eriksson@swengineer.se',
    subject: 'Password reset email never arrives',
    body: 'I clicked "Forgot Password" but no email has arrived after 30 minutes. I have checked my spam folder and allowlisted your domain. Is there a delay or is the email service down?',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(23),
  },
  {
    senderName: 'Uma Krishnan',
    senderEmail: 'uma.k@reportgen.in',
    subject: 'PDF export of monthly report is blank',
    body: 'When I export our monthly analytics report as PDF, the downloaded file is completely blank — just white pages. The same report renders correctly in the browser. This started happening last week.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(10),
  },
  {
    senderName: 'Vincent Dupont',
    senderEmail: 'v.dupont@domainops.fr',
    subject: 'Custom domain not resolving after DNS update',
    body: 'I updated the CNAME record as per your documentation 48 hours ago but the custom domain still shows a "DNS not configured" error in the dashboard. DNS propagation should be complete by now.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Wilma Stone',
    senderEmail: 'w.stone@auditco.com',
    subject: 'Audit log showing gaps in activity history',
    body: 'Our compliance team noticed the audit log is missing entries for March 15–17. All other periods look complete. We need to verify whether data was lost or if this is a display bug.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(11),
  },
  {
    senderName: 'Xenia Volkov',
    senderEmail: 'x.volkov@uxresearch.ru',
    subject: 'Dark mode preference not persisting between sessions',
    body: 'I switch to dark mode and it looks great, but every time I close and reopen the browser the interface is back to light mode. I have disabled any browser extensions that might interfere.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(32),
  },
  {
    senderName: 'Yannick Moreau',
    senderEmail: 'y.moreau@filters.be',
    subject: 'Date range filter not applying on Reports page',
    body: 'When I select a custom date range on the Reports page and click Apply, the data does not change. The URL updates to include the date parameters but the table still shows all-time data.',
    status: 'OPEN' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Zara Ahmed',
    senderEmail: 'z.ahmed@sessions.pk',
    subject: 'Session expiring after only 10 minutes',
    body: 'My session is expiring after about 10 minutes of inactivity, forcing me to log in repeatedly throughout the day. I have not configured any custom session timeout. The default should be much longer.',
    status: 'RESOLVED' as const,
    category: 'TECHNICAL_QUESTION' as const,
    createdAt: daysAgo(42),
  },

  // ── REFUND REQUESTS ───────────────────────────────────────────────────────
  {
    senderName: 'Adam Fletcher',
    senderEmail: 'adam.f@billingerror.com',
    subject: 'Charged twice for the same subscription',
    body: 'I was charged $49 twice on April 1st. I only have one active subscription and I only intended to pay once. My bank statement clearly shows two transactions to your company on the same day. Please refund the duplicate.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Bella Rossi',
    senderEmail: 'b.rossi@italy.it',
    subject: 'Refund for unused annual subscription',
    body: 'I paid for an annual plan in January but due to a change in company direction we no longer need the service. We have only used it for 2 months. Requesting a pro-rated refund for the remaining 10 months.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Connor Walsh',
    senderEmail: 'c.walsh@accident.ie',
    subject: 'Accidentally upgraded to the wrong plan',
    body: 'I accidentally clicked Upgrade and was immediately charged $199 for the Enterprise plan. I meant to select the $19 Starter plan. I have not used any Enterprise features. Please refund and downgrade my account.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(18),
  },
  {
    senderName: 'Donna Mills',
    senderEmail: 'donna.m@quickpay.us',
    subject: 'Accidental purchase — please process refund',
    body: 'My 8-year-old was playing on my laptop and somehow navigated to the checkout and completed a purchase. I received a $99 charge I did not authorise. Please refund as this was clearly a mistake.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(22),
  },
  {
    senderName: 'Edwin Park',
    senderEmail: 'e.park@downtime.kr',
    subject: 'Service was down for 3 days — requesting SLA credit',
    body: 'Your service was unavailable from March 10–12 (72 hours). Our team could not work during this time. Per your 99.9% uptime SLA, we are entitled to a service credit. Please apply the credit to our account.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(7),
  },
  {
    senderName: 'Freya Larsen',
    senderEmail: 'freya.l@unfulfilled.dk',
    subject: 'Paid for premium onboarding that was never delivered',
    body: 'We paid $500 for premium onboarding and a dedicated setup call. It has been 6 weeks and we have had no contact from your onboarding team despite multiple follow-up emails. Please refund the onboarding fee.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(8),
  },
  {
    senderName: 'Gary Mitchell',
    senderEmail: 'g.mitchell@trial.au',
    subject: 'Charged after cancelling during free trial',
    body: 'I cancelled my free trial on day 13 of a 14-day trial but was still charged the monthly fee. I have a confirmation email of my cancellation. Please refund the charge of $39.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Helena Kovacs',
    senderEmail: 'h.kovacs@unauthorized.hu',
    subject: 'Unauthorised card charge — not made by me',
    body: 'I noticed a $149 charge to your service on my credit card statement but I do not have an account with you. This appears to be fraud. Please refund immediately and help me identify the account using my card.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Ian Douglas',
    senderEmail: 'i.douglas@upgraded.nz',
    subject: 'Pro plan features not available after paying',
    body: 'I upgraded from Free to Pro 3 days ago and was charged $49 but my account still shows Free tier limits. I still cannot access the advanced reporting features that Pro is supposed to unlock.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(26),
  },
  {
    senderName: 'Jade Fontaine',
    senderEmail: 'j.fontaine@duplicate.ca',
    subject: 'Duplicate account charges for the same team',
    body: 'Our Finance team noticed we have been paying for two separate accounts for the same company. An admin set up a second account by mistake. Please merge them and refund the duplicate charges for the past 4 months.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(33),
  },
  {
    senderName: 'Kurt Zimmermann',
    senderEmail: 'k.zimm@renewal.ch',
    subject: 'Annual subscription renewed without prior notice',
    body: 'My annual plan auto-renewed yesterday for $588 without any reminder email. Had I received a notice I would have cancelled as we are moving to a different solution. Please refund the renewal.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(1),
  },
  {
    senderName: 'Lucy Adeyemi',
    senderEmail: 'l.adeyemi@cancelled.ng',
    subject: 'Billed for add-on I cancelled 2 months ago',
    body: 'I cancelled the Advanced Analytics add-on in February but I was charged for it in March and April. Confirmation email of cancellation attached. Please refund the two months of incorrect charges.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Max Bergmann',
    senderEmail: 'm.bergmann@competitor.de',
    subject: 'Switching to competitor — requesting pro-rated refund',
    body: 'We have decided to move to a competitor product that better fits our workflow. We are 2 months into an annual plan. As per your 30-day money-back guarantee does not apply after 30 days, but we wanted to inquire about a goodwill refund.',
    status: 'CLOSED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(88),
  },
  {
    senderName: 'Nadia Okonkwo',
    senderEmail: 'n.okonkwo@pricing.ng',
    subject: 'Overcharged due to pricing page error',
    body: 'The pricing page showed $29/month for the Pro plan when I subscribed. My credit card was charged $49/month. Screenshot of the pricing page attached. Please adjust the billing to the advertised price.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(44),
  },
  {
    senderName: 'Oscar Mendez',
    senderEmail: 'o.mendez@closed.mx',
    subject: 'Business closed — requesting refund for unused period',
    body: 'Unfortunately our company is closing down this month. We paid for an annual plan and have 8 months remaining. Given the circumstances, we are requesting a refund for the unused portion.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(9),
  },
  {
    senderName: 'Paula Santos',
    senderEmail: 'p.santos@currency.br',
    subject: 'Wrong currency applied to my invoice',
    body: 'My account is set to BRL but I was charged in USD at a poor exchange rate, costing me 20% more than expected. This is a system error on your end. Please reissue the invoice in BRL and refund the difference.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Ron Pierce',
    senderEmail: 'ron.p@mistake.us',
    subject: 'Upgraded by mistake — want immediate downgrade and refund',
    body: 'I was exploring the plan comparison page and accidentally hit the upgrade button. The charge of $199 went through immediately. I need this reversed ASAP as it exceeds my company expense limit.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(36),
  },
  {
    senderName: 'Sara Klimek',
    senderEmail: 's.klimek@sla.pl',
    subject: 'SLA violated last month — requesting service credit',
    body: 'According to your public status page, uptime in March was 98.7%, which is below the 99.9% guaranteed in our Enterprise SLA. I would like to claim the service credit as described in our contract.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(10),
  },
  {
    senderName: 'Tyler Brooks',
    senderEmail: 't.brooks@payment.us',
    subject: 'Payment processed but account not upgraded',
    body: 'I completed payment for the Pro plan ($49) 2 days ago. My bank confirms the transaction went through but my account is still on the Free tier. Please either upgrade my account or refund the charge.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(21),
  },
  {
    senderName: 'Uma Patel',
    senderEmail: 'uma.p@tax.in',
    subject: 'VAT incorrectly applied to our invoice',
    body: 'We are a B2B company and should be exempt from VAT under the reverse charge mechanism. Your system charged us 20% VAT on last month\'s invoice despite us providing our VAT number. Please issue a corrected invoice.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Victoria Cross',
    senderEmail: 'v.cross@unused.co.uk',
    subject: 'Refund request for add-on never used',
    body: 'I purchased the Advanced Reporting add-on 3 months ago intending to use it for a project that was subsequently cancelled. I never accessed the add-on at all. Is a refund possible for something completely unused?',
    status: 'CLOSED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(80),
  },
  {
    senderName: 'Will Turner',
    senderEmail: 'will.t@pirates.com',
    subject: 'Double charged after plan switch',
    body: 'I switched from monthly to annual billing mid-month. I was charged the prorated monthly fee AND the full annual fee on the same day. Please refund the monthly pro-rated charge as it should have been credited.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Xiomara Reyes',
    senderEmail: 'x.reyes@invoice.co',
    subject: 'Two invoices issued for the same billing period',
    body: 'I received two separate invoices for February — Invoice #1042 and Invoice #1043 — both for the same billing period and same amount. My card was charged twice. Please refund one and cancel the duplicate invoice.',
    status: 'RESOLVED' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(52),
  },
  {
    senderName: 'Yasmine Benali',
    senderEmail: 'y.benali@exchange.dz',
    subject: 'Charged for full month after downgrading',
    body: 'I downgraded from Business to Starter on March 3rd but was still charged the full Business plan price ($99) for March. I should have been charged only $29 for Starter. Please refund the $70 difference.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(7),
  },
  {
    senderName: 'Zachary Stone',
    senderEmail: 'z.stone@freeaccount.us',
    subject: 'Charged after supposedly free promo code',
    body: 'I applied promo code LAUNCH2026 which was advertised as "3 months free". The code appeared to apply at checkout but I was charged full price. Screenshots of the promo and checkout attached.',
    status: 'OPEN' as const,
    category: 'REFUND_REQUEST' as const,
    createdAt: daysAgo(4),
  },

  // ── UNCATEGORIZED ─────────────────────────────────────────────────────────
  {
    senderName: 'Abby Carter',
    senderEmail: 'abby.c@followup.com',
    subject: 'Following up on ticket #4821',
    body: "Hi, I submitted ticket #4821 last week about my API issue and haven't heard back. Just wanted to check if there's any update. The issue is still affecting our production system.",
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Brad Evans',
    senderEmail: 'brad.e@happy.com',
    subject: 'Just wanted to say — your product is amazing!',
    body: 'Hi team! I have been a customer for 6 months and just wanted to say how much your product has improved our workflow. The recent update was especially great. Keep up the excellent work!',
    status: 'CLOSED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(55),
  },
  {
    senderName: 'Cindy Park',
    senderEmail: 'cindy.p@enterprise.co',
    subject: 'Inquiry about custom enterprise plan',
    body: 'We are a 500-person company and the standard plans do not quite fit our needs. We need custom data retention, dedicated infrastructure, and a BAA for HIPAA compliance. Can we schedule a call to discuss?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Dan Foster',
    senderEmail: 'dan.f@roadmap.io',
    subject: 'Question about your product roadmap',
    body: 'We are deciding whether to invest in your platform long-term. Is there a public roadmap? Specifically we are interested in whether workflow automation and Zapier integration are planned for 2026.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Elena Popescu',
    senderEmail: 'e.popescu@partner.ro',
    subject: 'Partnership and reseller program inquiry',
    body: 'Our consulting firm works with SME clients across Eastern Europe. We are interested in becoming a reseller or implementation partner. Does such a program exist and whom should I speak to?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Frank Gibson',
    senderEmail: 'frank.g@techcrunch.com',
    subject: 'Media inquiry — feature story request',
    body: "Hi, I'm a journalist at TechCrunch writing a feature on the customer support SaaS space. I'd love to interview your founder or CEO. Could you pass this request to your PR team?",
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Gloria Mwangi',
    senderEmail: 'g.mwangi@suggestion.ke',
    subject: 'Feature suggestion: kanban view for tickets',
    body: "Love the product! One thing that would make a huge difference for our team is a Kanban board view for tickets — drag cards between OPEN / IN PROGRESS / RESOLVED columns. Is this on your radar?",
    status: 'CLOSED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(70),
  },
  {
    senderName: 'Harry Lewis',
    senderEmail: 'h.lewis@feedback.uk',
    subject: 'Feedback: recent navigation redesign is confusing',
    body: 'I understand the motivation behind the recent nav redesign, but the new layout makes it much harder to find commonly used features. The Settings menu in particular is now buried 3 levels deep.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(8),
  },
  {
    senderName: 'Ingrid Nilsson',
    senderEmail: 'i.nilsson@compliance.se',
    subject: 'Request for GDPR compliance documentation',
    body: 'Our DPO requires your Data Processing Agreement, Privacy Policy, and Sub-processor list for our vendor assessment. Could you send these documents or point me to where I can download them?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(9),
  },
  {
    senderName: 'James Osei',
    senderEmail: 'j.osei@security.gh',
    subject: 'Responsible disclosure: XSS vulnerability found',
    body: 'I am a security researcher and found a reflected XSS vulnerability in your search endpoint. The parameter "q" is rendered unsanitised. I am disclosing responsibly and request a private channel to share details.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(1),
  },
  {
    senderName: 'Karen Walsh',
    senderEmail: 'karen.w@scheduling.ie',
    subject: 'Requesting a call with your sales team',
    body: 'We are evaluating your Enterprise plan for a 200-seat deployment. Before committing, we would like a 30-minute demo call with your sales team to discuss our specific requirements. What is the best way to schedule this?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(2),
  },
  {
    senderName: 'Liam Murphy',
    senderEmail: 'liam.m@legal.ie',
    subject: 'Data Processing Agreement required',
    body: 'Our legal team requires a signed DPA before we can proceed with deployment. We process EU personal data so GDPR compliance is non-negotiable. Can you provide a standard DPA for review?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(3),
  },
  {
    senderName: 'Mia Schneider',
    senderEmail: 'm.schneider@enterprise.ch',
    subject: 'Enterprise pricing for 1000+ seats',
    body: 'We are a large enterprise evaluating your platform for company-wide deployment across 1200 users. The self-service pricing page only goes to 100 seats. Can we get a custom enterprise quote?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(4),
  },
  {
    senderName: 'Nathan Cross',
    senderEmail: 'n.cross@whitelabel.us',
    subject: 'White-label / OEM licensing inquiry',
    body: 'We are building a customer portal and are interested in licensing your product under our own brand. Do you offer white-label or OEM options? Who should I contact about licensing terms?',
    status: 'CLOSED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(95),
  },
  {
    senderName: 'Olivia Jensen',
    senderEmail: 'o.jensen@affiliate.dk',
    subject: 'Inquiry about affiliate program',
    body: 'I run a SaaS review blog with 50k monthly readers. I am interested in joining your affiliate or referral program. Do you have one, and if so, what are the commission rates?',
    status: 'RESOLVED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(48),
  },
  {
    senderName: 'Paul Vincent',
    senderEmail: 'p.vincent@legal.fr',
    subject: 'NDA required before product demo',
    body: 'Our company policy requires an NDA to be in place before vendor demos. Could you send over a mutual NDA for our legal team to review? We are keen to move forward with the evaluation.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(5),
  },
  {
    senderName: 'Queenie Tan',
    senderEmail: 'q.tan@ratelimits.sg',
    subject: 'Request to increase API rate limits',
    body: 'Our integration is production-ready but the standard API rate limit of 1000 req/min is a bottleneck during peak hours. We need at least 5000 req/min. Can we discuss an upgraded tier or enterprise plan?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(6),
  },
  {
    senderName: 'Roger Hunt',
    senderEmail: 'r.hunt@conference.us',
    subject: 'Conference sponsorship inquiry',
    body: 'I organise SupportCon, the largest customer support conference in North America. We have sponsorship packages starting at $5,000. Would your company be interested in being a sponsor for the 2026 event?',
    status: 'CLOSED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(100),
  },
  {
    senderName: 'Sandra Lee',
    senderEmail: 's.lee@university.edu',
    subject: 'Academic research data request',
    body: 'I am a PhD researcher at MIT studying customer support patterns. I would love anonymised aggregate data about support ticket resolution times for my research. Is this something your team would consider?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(7),
  },
  {
    senderName: 'Tom Baker',
    senderEmail: 't.baker@soc2.co.uk',
    subject: 'SOC 2 Type II report request',
    body: 'We are completing our vendor security review process. Could you share your most recent SOC 2 Type II report and your penetration test results? We are under NDA so this information will be kept confidential.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(8),
  },
  {
    senderName: 'Ulrika Holm',
    senderEmail: 'u.holm@feature.se',
    subject: 'Feature request: advanced analytics dashboard',
    body: 'It would be tremendously helpful to have a dedicated analytics dashboard showing ticket volume trends, average resolution times, agent performance metrics, and category breakdowns. Currently I have to export to Excel for this.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(9),
  },
  {
    senderName: 'Vince Romano',
    senderEmail: 'v.romano@onboarding.it',
    subject: 'Feedback: onboarding flow needs improvement',
    body: 'I just finished onboarding and found it quite confusing. The setup wizard has 12 steps and several steps require technical knowledge that most users will not have. A simplified mode for non-technical users would help.',
    status: 'RESOLVED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(57),
  },
  {
    senderName: 'Wanda Scott',
    senderEmail: 'w.scott@compliment.com',
    subject: 'Shoutout to your support agent Sarah',
    body: "I just want to say that Sarah from your support team went above and beyond to help resolve my billing issue last week. She was patient, knowledgeable, and incredibly helpful. Please pass on my thanks!",
    status: 'CLOSED' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(62),
  },
  {
    senderName: 'Xavier Obi',
    senderEmail: 'x.obi@investor.ng',
    subject: 'Investor relations inquiry',
    body: 'I represent a venture capital firm interested in your company. We would like to discuss potential investment opportunities. Could you connect me with the appropriate person on your leadership team?',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(10),
  },
  {
    senderName: 'Yvonne Beaumont',
    senderEmail: 'y.beaumont@uptime.fr',
    subject: 'Request for SLA and uptime documentation',
    body: 'Before signing an annual contract, our procurement team needs written documentation of your uptime SLA, incident response times, and historical uptime statistics for the past 12 months.',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(11),
  },
  {
    senderName: null,
    senderEmail: 'anonymous@tempmail.com',
    subject: 'Issue with login',
    body: 'login not working pls help',
    status: 'OPEN' as const,
    category: 'UNCATEGORIZED' as const,
    createdAt: daysAgo(1),
  },
]

async function seedTickets() {
  console.log(`Seeding ${tickets.length} tickets...`)

  await prisma.ticket.createMany({
    data: tickets.map((t) => ({
      ...t,
      updatedAt: t.createdAt,
    })),
    skipDuplicates: true,
  })

  const count = await prisma.ticket.count()
  console.log(`Done. Total tickets in DB: ${count}`)
  await prisma.$disconnect()
}

seedTickets().catch((err) => {
  console.error(err)
  process.exit(1)
})
